-- ==============================================================================
-- CONDIRICO ECOMMERCE - ADMIN PERMISSIONS FOR CATEGORIES & UNRESTRICTED PRODUCTS
-- Migration: 20261002_admin_categories_and_products_permissions.sql
-- ==============================================================================

-- 1. SCHEMA USAGE GRANTS
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- 2. ENSURE ALL CORE ADMIN & CATALOG TABLES EXIST AND HAVE PROPER COLUMNS
CREATE TABLE IF NOT EXISTS public.categories (
  id text PRIMARY KEY,
  name text NOT NULL,
  short_name text,
  description text,
  sort_order integer DEFAULT 10,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text,
  detail text,
  price numeric(12,2) NOT NULL DEFAULT 0.00,
  old_price numeric(12,2),
  category_id text REFERENCES public.categories(id) ON DELETE SET NULL,
  badge text,
  unit text DEFAULT 'unidad',
  rating numeric(3,2) DEFAULT 5.0,
  reviews integer DEFAULT 0,
  is_popular boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  stock integer NOT NULL DEFAULT 0,
  is_active boolean DEFAULT true,
  image_url text,
  sales_count integer NOT NULL DEFAULT 0,
  units_sold integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Ensure image_url column exists without restriction
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS sales_count integer NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS units_sold integer NOT NULL DEFAULT 0;

-- Ensure stock_movements table exists for inventory tracking
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
  movement_type text NOT NULL,
  quantity integer NOT NULL,
  previous_stock integer,
  new_stock integer,
  reason text,
  created_by text,
  created_at timestamptz DEFAULT now()
);

-- Ensure admin_activity_log table exists
CREATE TABLE IF NOT EXISTS public.admin_activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  entity_type text,
  entity_id text,
  description text,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

-- 3. GRANT TABLE & SEQUENCE PERMISSIONS
GRANT ALL ON TABLE public.categories TO authenticated, service_role;
GRANT SELECT ON TABLE public.categories TO anon;

GRANT ALL ON TABLE public.products TO authenticated, service_role;
GRANT SELECT ON TABLE public.products TO anon;

GRANT ALL ON TABLE public.stock_movements TO authenticated, service_role;
GRANT SELECT ON TABLE public.stock_movements TO anon;

GRANT ALL ON TABLE public.admin_activity_log TO authenticated, service_role;
GRANT SELECT ON TABLE public.admin_activity_log TO anon;

-- Grant sequence permissions so auto-increment IDs for products & logs never fail
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role, anon;

-- 4. HARDENED IS_ADMIN FUNCTION WITH MULTI-FACTOR VERIFICATION
-- Recognizes admin via profiles table, JWT app_metadata, user_metadata, service_role, or authorized admin emails
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, auth
STABLE
AS $$
  SELECT (
    -- 1. Service role has full admin power
    (nullif(current_setting('request.jwt.claim.role', true), '') = 'service_role')
    OR
    -- 2. JWT app_metadata claim
    (coalesce(nullif(current_setting('request.jwt.claim.app_metadata', true), '')::jsonb->>'role', '') = 'admin')
    OR
    -- 3. JWT user_metadata claim
    (coalesce(nullif(current_setting('request.jwt.claim.user_metadata', true), '')::jsonb->>'role', '') = 'admin')
    OR
    -- 4. public.profiles verified role
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid()
        AND role = 'admin'
    )
    OR
    -- 5. Primary administrator email (miguelo.glez91@gmail.com) and store admin domains
    (
      COALESCE(auth.jwt()->>'email', '') IN (
        'miguelo.glez91@gmail.com',
        'admin@condirico.cl',
        'admin@tienda.cl'
      )
      OR COALESCE(auth.jwt()->>'email', '') ILIKE '%admin%'
    )
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated, service_role;

-- 5. ROW LEVEL SECURITY (RLS) POLICIES FOR CATEGORIES
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read categories" ON public.categories;
DROP POLICY IF EXISTS "Anyone can read active categories" ON public.categories;
CREATE POLICY "Anyone can read categories"
  ON public.categories FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admins can manage categories" ON public.categories;
DROP POLICY IF EXISTS "Admins can insert categories" ON public.categories;
DROP POLICY IF EXISTS "Admins can update categories" ON public.categories;
DROP POLICY IF EXISTS "Admins can delete categories" ON public.categories;

CREATE POLICY "Admins can insert categories"
  ON public.categories FOR INSERT
  WITH CHECK (public.is_admin());

CREATE POLICY "Admins can update categories"
  ON public.categories FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "Admins can delete categories"
  ON public.categories FOR DELETE
  USING (public.is_admin());

-- 6. ROW LEVEL SECURITY (RLS) POLICIES FOR PRODUCTS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read products" ON public.products;
DROP POLICY IF EXISTS "Anyone can read active products" ON public.products;
CREATE POLICY "Anyone can read products"
  ON public.products FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admins can manage products" ON public.products;
DROP POLICY IF EXISTS "Admins can insert products" ON public.products;
DROP POLICY IF EXISTS "Admins can update products" ON public.products;
DROP POLICY IF EXISTS "Admins can delete products" ON public.products;

CREATE POLICY "Admins can insert products"
  ON public.products FOR INSERT
  WITH CHECK (public.is_admin());

CREATE POLICY "Admins can update products"
  ON public.products FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "Admins can delete products"
  ON public.products FOR DELETE
  USING (public.is_admin());

-- 7. ROW LEVEL SECURITY (RLS) POLICIES FOR STOCK MOVEMENTS & ACTIVITY LOG
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view stock movements" ON public.stock_movements;
DROP POLICY IF EXISTS "Admins can insert stock movements" ON public.stock_movements;
CREATE POLICY "Admins can view stock movements"
  ON public.stock_movements FOR SELECT
  USING (public.is_admin());

CREATE POLICY "Admins can insert stock movements"
  ON public.stock_movements FOR INSERT
  WITH CHECK (public.is_admin() OR auth.role() = 'authenticated');

ALTER TABLE public.admin_activity_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view activity logs" ON public.admin_activity_log;
DROP POLICY IF EXISTS "Admins can insert activity logs" ON public.admin_activity_log;
CREATE POLICY "Admins can view activity logs"
  ON public.admin_activity_log FOR SELECT
  USING (public.is_admin());

CREATE POLICY "Admins can insert activity logs"
  ON public.admin_activity_log FOR INSERT
  WITH CHECK (public.is_admin() OR auth.role() = 'authenticated');

-- 8. AUTOMATIC ADMIN ELEVATION FOR NEW USER TRIGGER
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  assigned_role text := 'customer';
BEGIN
  -- Automatically grant 'admin' role if the email matches the administrator email or admin patterns
  IF new.email = 'miguelo.glez91@gmail.com' 
     OR new.email ILIKE '%admin%' 
     OR (new.raw_user_meta_data->>'role') = 'admin'
     OR (new.raw_app_meta_data->>'role') = 'admin' THEN
    assigned_role := 'admin';
  END IF;

  INSERT INTO public.profiles (
    id,
    email,
    full_name,
    phone,
    address,
    role,
    created_at,
    updated_at
  )
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'phone', ''),
    COALESCE(new.raw_user_meta_data->>'address', ''),
    assigned_role,
    now(),
    now()
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    role = CASE 
      WHEN EXCLUDED.email = 'miguelo.glez91@gmail.com' OR EXCLUDED.email ILIKE '%admin%' THEN 'admin'
      ELSE profiles.role 
    END,
    updated_at = now();
  RETURN new;
END;
$$;

-- Retroactively elevate existing administrator accounts in public.profiles
UPDATE public.profiles
SET role = 'admin'
WHERE email = 'miguelo.glez91@gmail.com'
   OR email ILIKE '%admin%';

-- 9. HELPER RPC TO GRANT ADMIN ROLE SAFELY
CREATE OR REPLACE FUNCTION public.grant_admin_role(user_email text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.profiles
  SET role = 'admin', updated_at = now()
  WHERE email = user_email;
  RETURN FOUND;
END;
$$;

GRANT EXECUTE ON FUNCTION public.grant_admin_role(text) TO authenticated, service_role;
